#!/usr/bin/env python3

import sys

args = sys.argv



def main(flag):
    if flag in args:
        if flag == "-h":
            print("HELP")
        elif flag == "-b":
            print("BINARY")
    else:
        print("you ARE STUPID")
